---
- name: Ensure Poe hat fan configuration in /boot/firmware/config.txt
  hosts: all
  become: true  # Run tasks with elevated privileges

  tasks:
  - name: Insert PoE Hat Fan Speeds into config.txt
    blockinfile:
      path: /boot/firmware/config.txt
      block: |
        # PoE Hat Fan Speeds
        dtparam=poe_fan_temp0=58000
        dtparam=poe_fan_temp1=60000
        dtparam=poe_fan_temp2=62000
        dtparam=poe_fan_temp3=64000