---
  - name: Insert PoE Hat Fan Speeds into config.txt
    blockinfile:
      path: /boot/config.txt
      block: |
        # PoE Hat Fan Speeds
        dtparam=poe_fan_temp0=50000
        dtparam=poe_fan_temp1=54000
        dtparam=poe_fan_temp2=58000
        dtparam=poe_fan_temp3=62000