---
  - name: Remove PoE Hat Fan Speeds from config.txt
    lineinfile:
      path: /boot/config.txt
      line: '{{ item }}'
      state: absent
      create: no
    with_items:
      - '# BEGIN ANSIBLE MANAGED BLOCK'
      - '# PoE Hat Fan Speeds'
      - 'dtparam=poe_fan_temp0=50000'
      - 'dtparam=poe_fan_temp1=54000'
      - 'dtparam=poe_fan_temp2=58000'
      - 'dtparam=poe_fan_temp3=62000'
      - '# END ANSIBLE MANAGED BLOCK'