---
- name: Install neofetch package
  hosts: virtualmachines
  become: yes  # This is used to escalate privileges (sudo)
  tasks:
    - name: Update package cache (apt for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install neofetch (apt for Debian/Ubuntu)
      apt:
        name: neofetch
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Update package cache (yum for CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Install neofetch (yum for CentOS)
      yum:
        name: neofetch
        state: present
      when: ansible_os_family == 'RedHat'
