---
- name: Copy and make file executable
  hosts: virtualmachines
  become: yes  # Use sudo to become a privileged user
  tasks:
    - name: Download display file from GitHub
      get_url:
        url: https://github.com/mdelgert/PiRackPro/raw/main/SKU_RM0004/display
        dest: /usr/bin/display
        mode: '0755'  # Set the file permissions to make it executable
    - name: Add display to rc.local
      lineinfile:
        path: /etc/rc.local
        insertbefore: '^\s*exit 0'
        line: 'display &'
    - name: Backup /boot/config.txt
      copy:
        src: /boot/config.txt
        dest: /boot/config.txt.bak
      register: backup_result
      ignore_errors: yes  # Ignore errors if the file doesn't exist
    - name: Replace /boot/config.txt with new content
      get_url:
        url: https://raw.githubusercontent.com/mdelgert/PiRackPro/main/ansible/config.txt
        dest: /boot/config.txt
    - name: Reboot the system
      reboot: