---
- name: Copy and make file executable
  hosts: rackmachines
  become: yes  # Use sudo to become a privileged user
  tasks:
    - name: Backup /etc/modules
      copy:
        src: /etc/modules
        dest: /etc/modules.bak
      register: backup_result

    - name: Backup /etc/rc.local
      copy:
        src: /etc/rc.local
        dest: /etc/rc.local.bak
      register: backup_result

    - name: Backup /boot/config.txt
      copy:
        src: /boot/config.txt
        dest: /boot/config.txt.bak
      register: backup_result

      ignore_errors: yes  # Ignore errors if the file doesn't exist
    # - name: Add line above exit 0 in rc.local
    #   lineinfile:
    #     path: /etc/rc.local
    #     insertbefore: '^\s*exit 0'
    #     line: 'display &'

    - name: Read the content of /etc/rc.local
      slurp:
        src: /etc/rc.local
      register: rc_local_content

    - name: Add "display &" to /etc/rc.local if not present
      lineinfile:
        path: /etc/rc.local
        insertbefore: '^exit 0$'
        line: 'display &'
      when: "'display &' not in rc_local_content.content | b64decode"

    - name: Replace /boot/config.txt with new content
      get_url:
        url: https://raw.githubusercontent.com/mdelgert/PiRackPro/main/ansible/config.txt
        dest: /boot/config.txt

    - name: Replace /etc/modules with new content
      get_url:
        url: https://raw.githubusercontent.com/mdelgert/PiRackPro/main/ansible/modules
        dest: /etc/modules

    - name: Download display file from GitHub
      get_url:
        url: https://github.com/mdelgert/PiRackPro/raw/main/SKU_RM0004/display
        dest: /usr/bin/display
        mode: '0755'  # Set the file permissions to make it executable
        
    - name: Reboot the system
      reboot: